# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "2.0.0.{build}"

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: x64

configuration: Release

build:
  project: FcsSdkNet.sln          # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  #include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal

# scripts to run before build
before_build:
    - nuget restore

test:
  assemblies:
    - Test\UnitTests\**\UnitTests.dll

nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: Src\**\*.nupkg


#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# deploy:
#   - provider: NuGet
#     api_key:
#       secure: acA5IpwmiKf6lWbfGhvfZWN4vA7QZtz4sp5Mr99vtrYPzFJcecMCoP5CEDm27N2c
#     skip_symbols: false
#     artifact: /.*\.nupkg/
